model_params:
  model: MNISTNet
  num_classes: 10

args:
  expdir: src
  logdir: logs
  verbose: True

stages:
  data_params:
    batch_size: 64
    num_workers: 0
    train_dir: "./data/train"
    valid_size: 0.2
    loaders_params:
      valid:
        batch_size: 128

  state_params:
    num_epochs: 3
    main_metric: accuracy01
    minimize_metric: False

  criterion_params:
    criterion: CrossEntropyLoss

  optimizer_params:
    optimizer: Adam

  callbacks_params:
    accuracy:
      callback: AccuracyCallback
      accuracy_args: [1, 3]

  stage1: {}
